Добавлено решение дз №3
Daniil4639/Tinkoff_Repository pull request #6
Opened 2023-10-22 20:01 UTC by Daniil4639

2023-11-06 20:45 UTC, VictorMinsky requested changes
Добавь меня, пожалуйста, в контрибьюторы репозитория, чтобы я мог резолвить треды с замечаниями.

Гайд -- https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task1.java
> +    private static final int NUMBER130 = 130;
Сначала поля, потом конструкторы, потом методы

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task1.java
Каждое задание должно быть в своём пакете (папке)

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task1.java
> +    private static final int NUMBER130 = 130;
Не сильно понятное название констант, если быть точнее, то 0 новой информации.

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task2.java
> +    public static ArrayList<String> clusterize(String receivedString) {
`public static List<String> clusterize(String receivedString) `

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task2.java
> +        ArrayList<String> arrayOfTokens = new ArrayList<>();
Слева обычно указывают интерфейс (здесь `List`), справа реализацию (здесь `ArrayList`)

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task3.java
> +        for (int iterator = 0; iterator < receivedArray.size(); iterator++) {
Сделай через for-each loop

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task4.java
> +            result += ROMAN_DIGITS.get(valueArray[mapIterator]);
Складываешь строки в цикле, это `O(n^2)`. Используй `StringBuilder`

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task5.java
> +                    String[] firstArray = firstStr.split(" ");
`\\s+`

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task5.java
> +            });
Вынеси в класс

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task5.java
> +            });
Кажется, что один компаратор можно реализовать через другой, чтобы не было такой копипасты

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task5.java
> +                    }
Ещё у тебя нарушается контракт, ты не возвращаешь 0, когда объекты одинаковые

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task6.java
> +        }
Unused

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task6.java
> +            }
`return Integer.compare(0, value);`

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task6.java
> +                    Stock oldStock = iterator.next();
```
            for (Stock stock : stockPriorityQueue) {
                ...
            }
```

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task6.java
> +                }
Инвертируй всё условия, чтобы убрать вложенность. Например не 
```
                if (iterator.hasNext()) {
                    ...
                } else {
                    break;
                }
```
А
```
                if (!iterator.hasNext()) {
                    break;
                } 
                    ...
```

2023-11-06 20:45 UTC, VictorMinsky commented on src/test/java/edu/hw3/Task7Test.java
> +        TreeMap<String, String> tree = new TreeMap<>(Comparator.nullsFirst(Comparator.naturalOrder()));
Молодец, что знаешь про такое, но в задание было написано `...Напишите и...`

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task8.java
> +        private Collection<T> internalCollection;
`private final`

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task8.java
> +            return (T) internalCollection.toArray()[currentIndex--];
Ты кастишь весь список в массив каждый раз при получении элемента. Храни внутри не Collection<T>, а List<T>, тогда такой проблемы не будет

2023-11-06 20:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task8.java
> +            return currentIndex >= 0 && internalCollection.toArray()[currentIndex] != null;
А почему null-ы не могут лежать в списке? Например, передав коллекцию вот так `Arrays.asList(1, 2, 3, null)`

2023-11-07 16:05 UTC, Daniil4639 reviewed
Добавлены изменения

2023-11-07 17:55 UTC, VictorMinsky approved these changes
OK

Ещё по мелочи:
1) Стоит оставлять какой-то комментарий в каждом ишью, даже если это просто fixed, согл или что-то более подробное
2) Ишью обычно резолвит тот, кто их оставил, чтобы убедиться, что всё правильно было исправлено. Тебе не стоит это делать

2023-11-07 17:55 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task5/Task5.java
> +    public static final class SecondNameComparator implements Comparator<String> {
Хорош, ещё бы этот класс в отдельный файл вынести)

2023-11-10 18:58 UTC, merged