добавлено решение дз №4
Daniil4639/Tinkoff_Repository pull request #7
Opened 2023-10-26 20:46 UTC by Daniil4639

2023-11-09 20:47 UTC, VictorMinsky requested changes
Исправь замечания и переделай все задания, где ты используешь не стримы

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/UsingClasses.java
> +    private final static String FIELD_IS_NEGATIVE = ": is negative\n";
`\n` это UNIX перевод строки. В Винде и старых маках он другой. Используй `System.lineSeparator()`

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/UsingClasses.java
> +    private final static ArrayList<Integer> PAWS_COUNT = new ArrayList<>(asList(4, 2, 0, 8));
Кажется, что твой хардкод не лучше хардкода из условия:
```java
    public int paws() {
        return switch (type) {
            case CAT, DOG -> 4;
            case BIRD -> 2;
            case FISH -> 0;
            case SPIDER -> 8;
        };
    }
```

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/UsingClasses.java
> +                case SPIDER -> PAWS_COUNT.get(PAWS_COUNT.size()) - 1;
А ты с индексами не касякнул, -1 вроде не там делаешь? Ты просишь `n` элемент у списка, это `IndexOutOfBoundsException`. Вообще странно как у тебя прошёл пайплайн

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/UsingClasses.java
> +                case SPIDER -> PAWS_COUNT.get(PAWS_COUNT.size()) - 1;
А вот и не прошёл, я перезапустил)

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/UsingClasses.java
> +        }
Функции 1 в 1, а `checkBites` вообще unused. Всё окей?

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/UsingClasses.java
> +            field.setAccessible(true);
А объясни зачем ты занимаешься рефлексией? Кажется, что можно сделать без этого

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +    // func 1
Молодец, что смапил функции в задачи, но было бы неплохо, если бы ты писал условно
```java
// Задача 1: Отсортировать животных по росту от самого маленького к самому большому -> List<Animal>
```
Тогда мне не пришлось бы смотреть в условие)

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +    public static void heightAnimalSort(List<UsingClasses.Animal> receivedAnimals) {
А чего `void` то, не ожидается, что мы будем менять входную коллекцию

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +        receivedAnimals.sort(Comparator.comparingInt(UsingClasses.Animal::height));
Используй стримы здесь и в других заданиях. Их можно сделать полностью на стримах (где-то записывая промежуточные значения в переменные)

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +        List<UsingClasses.Animal> receivedAnimals, int neededAnimalsCount) {
Так никто не форматирует, допускается такой стиль, когда аргументы не помещаются в одну строку
```java
    public static List<UsingClasses.Animal> weightAnimalSort(
        List<UsingClasses.Animal> receivedAnimals,
        int neededAnimalsCount
    ) {
        List<UsingClasses.Animal> newAnimalList = new ArrayList<>(List.copyOf(receivedAnimals));

        newAnimalList.sort(Comparator.comparingInt(UsingClasses.Animal::weight));

        return newAnimalList.reversed().stream().limit(neededAnimalsCount).collect(Collectors.toList());
    }
```

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +        return newAnimalList.reversed().stream().limit(neededAnimalsCount).collect(Collectors.toList());
Попробуй переписать все остальные таски тоже на стримы в таком формате. Всё-таки суть этой домашки познакомить вас со стримами, а ты их почти не используешь( 

```java
        return receivedAnimals
            .stream()
            .sorted(Comparator.comparingInt(UsingClasses.Animal::weight).reversed())
            .limit(neededAnimalsCount)
            .toList();
```

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +        final int MINIMUM_HEIGHT = 100;
В поле класса

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +                && it.height() > receivedHeight).toList().isEmpty();
Стримы принято записывать по одной операции в строке:
```java
        return !receivedAnimals.stream()
            .filter(it -> it.type().equals(UsingClasses.Animal.Type.DOG) && it.height() > receivedHeight)
            .toList()
            .isEmpty();
```

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +        return newAnimalList;
Утверждается, что ВСЕ задания можно сделать чисто на стримах.
```java
        return receivedAnimals.stream()
            .sorted(Comparator
                .comparing(UsingClasses.Animal::type)
                .thenComparing(UsingClasses.Animal::sex)
                .thenComparing(UsingClasses.Animal::name))
            .toList();
```

2023-11-09 20:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +                }
Кажется, что у тебя компаратор неправильно сортирует

2023-11-10 13:11 UTC, Daniil4639 commented on src/main/java/edu/hw4/Task.java
> +                }
Он сортировал тип животного лексикографически. Я сначала подумал, что так надо. Исправил на сортировку по enum. Скоро отправлю доработанный код.

2023-11-12 16:47 UTC, VictorMinsky approved these changes
OK

Смотри, ишью обычно резолвит тот, кто их оставил, чтобы проверить, что ты действительно правильно понял и исправил замечания, это должен делать не ты.

2023-11-12 16:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
>          List<UsingClasses.Animal> receivedAnimals) {
Не исправил форматирование аргументов

https://github.com/Daniil4639/Tinkoff_Repository/pull/7#discussion_r1388548137

2023-11-13 07:01 UTC, merged